return {
    rrn: elem.rrn,
    identifier: index,
    accountApplicationId: props.state.applicationId,
    businessOfficialTypeStr: elem.officialType,
    shareholderType: elem.officialShareHolderType,
    name: elem.name,
    share: Number(elem.officialShare),
    belongingEntity: elem.officialBelongingEntity,
     
    // nationality: elem.officialNationality,
    dateOfBirth: elem.officialDateOfBirth
      ? elem.officialDateOfBirth.split('T')[0]
      : '',
    countryOfBirth: elem.officialCountryOfBirth,
    address: elem.officialAddress,
    countryOfAddress: elem.officialCountryAddress,
    docList: officialFileHelper.getDocList(
      elem.docList,
      elem.officialType
    ),
  };




  [
    {
        "unifiedId": "8800000377",
        "expiryDate": "2022-09-22T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "S P L ",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008158  - شركة الشخص الواحد ذ م م",
        "partnerNameEnglish": "Ali  Abdallah",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة الشخص الواحد ذ م م",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3015543",
        "establishmentDate": "2021-09-23T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "RAVISANKAR REDDY KASU RAVISANKAR REDDY KASU RAVISANKAR REDDY KASU RAVISANKAR REDDY KASU",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008158  - SOLE PROPRIETORSHIP L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Sole Proprietorship L.L.C."
    },
    {
        "unifiedId": "8800000401",
        "expiryDate": "2022-10-08T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "تستنج انستنت",
        "partnerNameEnglish": "Ali  Abdallah",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3016437",
        "establishmentDate": "2021-10-09T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "Ali  Abdallah Ali  Abdallah Ali  Abdallah Ali  Abdallah",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "TESTING INSTANT",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000406",
        "expiryDate": "2022-10-09T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "تستنج إكسستنغ نايم",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3016470",
        "establishmentDate": "2021-10-10T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "TESTING EXISTING NAME",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000402",
        "expiryDate": "2022-10-09T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "تستنج إنستنتفء",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3016473",
        "establishmentDate": "2021-10-10T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "TESTING INSTANTV2",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000403",
        "expiryDate": "2022-10-09T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "تستنج إنستنتفع",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3016487",
        "establishmentDate": "2021-10-10T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "TESTING INSTANTV3",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000404",
        "expiryDate": "2022-10-09T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "L L C ",
        "partnerPercentage": "49",
        "tradeNameArabic": "كوستكوفي للمواشى ذ.م.م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "شركة ذات مسؤولية محدودة",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3016489",
        "establishmentDate": "2021-10-10T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "COSTACOFEE LIVESTOCK L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Limited Liability Company"
    },
    {
        "unifiedId": "8800000408",
        "expiryDate": "2022-10-10T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "L L C ",
        "partnerPercentage": "51",
        "tradeNameArabic": "تستنغبلود موا ذ.م.م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة ذات مسؤولية محدودة",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3016491",
        "establishmentDate": "2021-10-11T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "TESTINGUPLOAD MOA L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Limited Liability Company"
    },
    {
        "unifiedId": "8800000407",
        "expiryDate": "2022-10-09T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "S P L ",
        "partnerPercentage": "100",
        "tradeNameArabic": "صلي أنس تستنج موا ديجيتال - شركة الشخص الواحد ذ م م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة الشخص الواحد ذ م م",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3016554",
        "establishmentDate": "2021-10-10T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "SOLE ANAS TESTING MOA DIGITAL - SOLE PROPRIETORSHIP L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Sole Proprietorship L.L.C."
    },
    {
        "unifiedId": "8800000419",
        "expiryDate": "2022-10-11T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008447",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3016608",
        "establishmentDate": "2021-10-12T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008447",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000415",
        "expiryDate": "2022-10-11T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "L L C ",
        "partnerPercentage": "51",
        "tradeNameArabic": "1008453 التجارة ذ.م.م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "شركة ذات مسؤولية محدودة",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3016622",
        "establishmentDate": "2021-10-12T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008453 TRADING L.L.C",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Limited Liability Company"
    },
    {
        "unifiedId": "8800000414",
        "expiryDate": "2022-10-11T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "S P L ",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008455 العقارات  - شركة الشخص الواحد ذ م م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "شركة الشخص الواحد ذ م م",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3016626",
        "establishmentDate": "2021-10-12T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008455 REAL ESTATE  - SOLE PROPRIETORSHIP L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Sole Proprietorship L.L.C."
    },
    {
        "unifiedId": "8800000427",
        "expiryDate": "2022-10-12T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "تك شموستي",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3016639",
        "establishmentDate": "2021-10-13T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "TECH CHEMWASTE",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000425",
        "expiryDate": "2022-10-12T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "S P L ",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008459  - شركة الشخص الواحد ذ م م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة الشخص الواحد ذ م م",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3016670",
        "establishmentDate": "2021-10-13T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008459  - SOLE PROPRIETORSHIP L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Sole Proprietorship L.L.C."
    },
    {
        "unifiedId": "8800000430",
        "expiryDate": "2022-10-13T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "S P L ",
        "partnerPercentage": "100",
        "tradeNameArabic": "تك شموستي أن - شركة الشخص الواحد ذ م م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة الشخص الواحد ذ م م",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3016779",
        "establishmentDate": "2021-10-14T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "TECH CHEMWASTE ONE - SOLE PROPRIETORSHIP L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Sole Proprietorship L.L.C."
    },
    {
        "unifiedId": "8800000431",
        "expiryDate": "2022-10-13T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008480 العقارات",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3016793",
        "establishmentDate": "2021-10-14T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008480 REAL ESTATE",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000432",
        "expiryDate": "2022-10-13T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "S P L ",
        "partnerPercentage": "100",
        "tradeNameArabic": "شانل - شركة الشخص الواحد ذ م م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة الشخص الواحد ذ م م",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3016805",
        "establishmentDate": "2021-10-14T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "CHANEL - SOLE PROPRIETORSHIP L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Sole Proprietorship L.L.C."
    },
    {
        "unifiedId": "8800000433",
        "expiryDate": "2022-10-13T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "L L C ",
        "partnerPercentage": "51",
        "tradeNameArabic": "تستنج أبلودموة ذ.م.م",
        "partnerNameEnglish": "Ali Abdallah",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة ذات مسؤولية محدودة",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3016809",
        "establishmentDate": "2021-10-14T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "علي  عبد الله علي  عبد الله علي  عبد الله علي  عبد الله",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "TESTING UPLOADMOA L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Limited Liability Company"
    },
    {
        "unifiedId": "8800000437",
        "expiryDate": "2022-10-18T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "L L C ",
        "partnerPercentage": "51",
        "tradeNameArabic": "أجكمبني ذ.م.م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "شركة ذات مسؤولية محدودة",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3016973",
        "establishmentDate": "2021-10-19T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "AGGCOMPANY L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Limited Liability Company"
    },
    {
        "unifiedId": "8800000472",
        "expiryDate": "2022-11-02T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008543 التفصيل والخياطة",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3016992",
        "establishmentDate": "2021-11-03T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008543 SEWING AND TAILORING",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000440",
        "expiryDate": "2022-10-23T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "تستنج فر إنفسنس",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017001",
        "establishmentDate": "2021-10-24T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "TESTING FOR INVISONS",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000445",
        "expiryDate": "2022-10-23T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "تستنج إمندف",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017075",
        "establishmentDate": "2021-10-24T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "TESTING EMANDPH",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000450",
        "expiryDate": "2022-10-24T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "S P L ",
        "partnerPercentage": "100",
        "tradeNameArabic": "كمبكمركيلس - شركة الشخص الواحد ذ م م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة الشخص الواحد ذ م م",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017130",
        "establishmentDate": "2021-10-25T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "CUMPCOMMERCIALS - SOLE PROPRIETORSHIP L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Sole Proprietorship L.L.C."
    },
    {
        "unifiedId": "8800000451",
        "expiryDate": "2022-10-25T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008565 العقارات",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3017150",
        "establishmentDate": "2021-10-26T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008565 REAL ESTATE",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000452",
        "expiryDate": "2022-10-25T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008566 العقارات",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3017152",
        "establishmentDate": "2021-10-26T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008566 REAL ESTATE",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000455",
        "expiryDate": "2022-10-26T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008572 المطاعم",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3017223",
        "establishmentDate": "2021-10-27T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008572 RESTAURANTS",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000464",
        "expiryDate": "2022-10-28T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "S P L ",
        "partnerPercentage": "100",
        "tradeNameArabic": "إنستكريم  - شركة الشخص الواحد ذ م م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "شركة الشخص الواحد ذ م م",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3017292",
        "establishmentDate": "2021-10-29T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "INSTACREAM  - SOLE PROPRIETORSHIP L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Sole Proprietorship L.L.C."
    },
    {
        "unifiedId": "8800000469",
        "expiryDate": "2022-10-31T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008588 المطاعم",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3017373",
        "establishmentDate": "2021-11-01T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008588 RESTAURANTS",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000470",
        "expiryDate": "2022-10-31T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "S P L ",
        "partnerPercentage": "100",
        "tradeNameArabic": "سالم- شركة الشخص الواحد ذ م م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة الشخص الواحد ذ م م",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017398",
        "establishmentDate": "2021-11-01T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "SALEM- SOLE PROPRIETORSHIP L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Sole Proprietorship L.L.C."
    },
    {
        "unifiedId": "8800000475",
        "expiryDate": "2022-11-03T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008599 العقارات",
        "partnerNameEnglish": "Ali  Abdallah",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017554",
        "establishmentDate": "2021-11-04T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "Ali  Abdallah Ali  Abdallah Ali  Abdallah Ali  Abdallah",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008599 REAL ESTATE",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000534",
        "expiryDate": "2023-01-24T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "S P L ",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008600  - شركة الشخص الواحد ذ م م",
        "partnerNameEnglish": "Ali  Abdallah Abdallah",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة الشخص الواحد ذ م م",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017565",
        "establishmentDate": "2022-01-25T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "علي  عبد الله علي  عبد الله علي  عبد الله علي  عبد الله",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008600  - SOLE PROPRIETORSHIP L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Sole Proprietorship L.L.C."
    },
    {
        "unifiedId": "8800000476",
        "expiryDate": "2022-11-06T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "S P L ",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008601 المطاعم  - شركة الشخص الواحد ذ م م",
        "partnerNameEnglish": "Ali  Abdallah",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة الشخص الواحد ذ م م",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017574",
        "establishmentDate": "2021-11-07T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "Ali  Abdallah Ali  Abdallah Ali  Abdallah Ali  Abdallah",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008601 RESTAURANTS  - SOLE PROPRIETORSHIP L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Sole Proprietorship L.L.C."
    },
    {
        "unifiedId": "8800000478",
        "expiryDate": "2022-11-07T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "S P L ",
        "partnerPercentage": "100",
        "tradeNameArabic": "كمثل - شركة الشخص الواحد ذ م م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة الشخص الواحد ذ م م",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017635",
        "establishmentDate": "2021-11-08T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "COMOSOLE - SOLE PROPRIETORSHIP L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Sole Proprietorship L.L.C."
    },
    {
        "unifiedId": "8800000479",
        "expiryDate": "2022-11-07T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "S P L ",
        "partnerPercentage": "100",
        "tradeNameArabic": "إتشليرننغ - شركة الشخص الواحد ذ م م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة الشخص الواحد ذ م م",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017655",
        "establishmentDate": "2021-11-08T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "ITECHLEARNING - SOLE PROPRIETORSHIP L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Sole Proprietorship L.L.C."
    },
    {
        "unifiedId": "8800000481",
        "expiryDate": "2022-11-07T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "NA",
        "partnerPercentage": "100",
        "tradeNameArabic": "إتشليرننغ - شركة الشخص الواحد ذ م م -  فرع",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "فرع محلية- ابو ظبي",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017673",
        "establishmentDate": "2021-11-08T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "ITECHLEARNING - SOLE PROPRIETORSHIP L.L.C. - BRANCH",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Local Branch"
    },
    {
        "unifiedId": "8800000482",
        "expiryDate": "2022-11-08T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "L L C ",
        "partnerPercentage": "60",
        "tradeNameArabic": "1008606 المطاعم ذ.م.م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "شركة ذات مسؤولية محدودة",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3017684",
        "establishmentDate": "2021-11-09T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008606 RESTAURANTS L.L.C",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Limited Liability Company"
    },
    {
        "unifiedId": "8800000483",
        "expiryDate": "2022-11-08T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008609 العقارات",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3017690",
        "establishmentDate": "2021-11-09T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008609 REAL ESTATE",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000484",
        "expiryDate": "2022-11-09T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "L L C ",
        "partnerPercentage": "60",
        "tradeNameArabic": "كمبتفرش ذ.م.م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة ذات مسؤولية محدودة",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017716",
        "establishmentDate": "2021-11-10T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "COMBATFRESH L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Limited Liability Company"
    },
    {
        "unifiedId": "8800000486",
        "expiryDate": "2022-11-09T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008615 المطاعم",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3017726",
        "establishmentDate": "2021-11-10T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008615 RESTAURANTS",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000487",
        "expiryDate": "2022-11-09T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "تكنوتريت",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017732",
        "establishmentDate": "2021-11-10T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "TECHNOTRAIT",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000488",
        "expiryDate": "2022-11-09T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "L L C ",
        "partnerPercentage": "60",
        "tradeNameArabic": "رتيلتركس ذ.م.م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة ذات مسؤولية محدودة",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017733",
        "establishmentDate": "2021-11-10T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "RETAILTRACKS L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Limited Liability Company"
    },
    {
        "unifiedId": "8800000489",
        "expiryDate": "2022-11-10T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008620 المطاعم",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3017784",
        "establishmentDate": "2021-11-11T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008620 RESTAURANTS",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000490",
        "expiryDate": "2022-11-14T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008622 التفصيل والخياطة",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3017821",
        "establishmentDate": "2021-11-15T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008622 SEWING AND TAILORING",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000492",
        "expiryDate": "2022-11-15T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "سورية",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017835",
        "establishmentDate": "2021-11-16T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "SURYA",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000495",
        "expiryDate": "2022-11-15T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008632 المطاعم",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3017854",
        "establishmentDate": "2021-11-16T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008632 RESTAURANTS",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000499",
        "expiryDate": "2022-11-17T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "L L C ",
        "partnerPercentage": "60",
        "tradeNameArabic": "رغنتش ذ.م.م",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "شركة ذات مسؤولية محدودة",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017898",
        "establishmentDate": "2021-11-18T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "ROGUNITECH L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Limited Liability Company"
    },
    {
        "unifiedId": "8800000502",
        "expiryDate": "2022-11-21T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "كومرس",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017949",
        "establishmentDate": "2021-11-22T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "COMMERS",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000503",
        "expiryDate": "2019-11-22T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008650",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-3017996",
        "establishmentDate": "2021-11-23T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": null,
        "issuePlaceArabic": null,
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008650",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000507",
        "expiryDate": "2022-12-06T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008659 المطاعم",
        "partnerNameEnglish": "Noushad Kuttan Aatif Mukhia",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3018087",
        "establishmentDate": "2021-12-07T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "نوشاد كتان اتيف موخيا",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008659 RESTAURANTS",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    }
]
