[
    {
        "unifiedId": "43",
        "expiryDate": "2022-03-20T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1003611 الخدمات",
        "partnerNameEnglish": "Abbas Anas Naganathan",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-2973345",
        "establishmentDate": "2020-03-21T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "عباس انس  ناجاناثان",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1003611 SERVICES",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "107",
        "expiryDate": "2022-04-02T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "اسواق اختبار ",
        "partnerNameEnglish": "Xiaoping Mei",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-2974449",
        "establishmentDate": "2020-04-03T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "زياوبينج   مى",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": " TEST MARKET",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "121",
        "expiryDate": "2022-04-05T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "تم إكو استن",
        "partnerNameEnglish": "Abbas Anas Naganathan",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-2974771",
        "establishmentDate": "2020-04-06T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "عباس انس  ناجاناثان",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "TAMM ECO ESTN",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "139",
        "expiryDate": "2022-04-09T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": " عند للديكور و الصيانة العامة",
        "partnerNameEnglish": "Abbas Anas Naganathan",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-2975175",
        "establishmentDate": "2020-04-10T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "عباس انس  ناجاناثان",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": " INDU DECORATION & GENERAL MAINTENANCE",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "271",
        "expiryDate": "2022-06-15T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "كجكلجلكج",
        "partnerNameEnglish": "Abbas Anas Naganathan",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-2978720",
        "establishmentDate": "2020-06-16T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "عباس انس  ناجاناثان",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "KJKKLJLKJ",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "273",
        "expiryDate": "2022-06-15T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": " أدس للعقارات",
        "partnerNameEnglish": "Abbas Anas Naganathan",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-2978724",
        "establishmentDate": "2020-06-16T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "عباس انس  ناجاناثان",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": " ADS REAL ESTATE",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "10001396",
        "expiryDate": "2022-07-04T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1005585 الخدمات",
        "partnerNameEnglish": "Abbas Naganathan",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-2979896",
        "establishmentDate": "2020-07-05T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "E-SERVICES",
        "issuePlaceArabic": "الإنترنت",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": null,
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1005585 SERVICES",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "475",
        "expiryDate": "2022-08-16T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "مكتبة إمبرتسدفد",
        "partnerNameEnglish": "Abbas Anas Naganathan",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الإمارات العربية المتحدة",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "ARE",
        "tradeLicenseNo": "CN-2982000",
        "establishmentDate": "2020-08-17T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "عباس انس  ناجاناثان",
        "partnerNationalityEnglish": "United Arab Emirates",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "IMPORTSDFD BOOKSHOP",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000272",
        "expiryDate": "2022-08-02T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1007826",
        "partnerNameEnglish": "Abbas Anas Naganathan",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3014253",
        "establishmentDate": "2021-08-03T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "عباس انس  ناجاناثان",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1007826",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000273",
        "expiryDate": "2022-08-02T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1007830",
        "partnerNameEnglish": "Abbas Anas Naganathan",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3014262",
        "establishmentDate": "2021-08-03T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "عباس انس  ناجاناثان",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1007830",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000428",
        "expiryDate": "2022-10-12T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "تستنجلك أبلودموة كم ذ.م.م",
        "partnerNameEnglish": "Abbas Anas Naganathan",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3016762",
        "establishmentDate": "2021-10-13T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "عباس انس  ناجاناثان",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "TESTINGLLC UPLOADMOA COMM L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000433",
        "expiryDate": "2022-10-13T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "L L C ",
        "partnerPercentage": "49",
        "tradeNameArabic": "تستنج أبلودموة ذ.م.م",
        "partnerNameEnglish": "Ray   Izz Izz",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "شركة ذات مسؤولية محدودة",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3016809",
        "establishmentDate": "2021-10-14T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "Ray   Izz Ray   Izz Ray   Izz Ray   Izz",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "TESTING UPLOADMOA L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Limited Liability Company"
    },
    {
        "unifiedId": "8800000435",
        "expiryDate": "2022-10-14T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "EST",
        "partnerPercentage": "100",
        "tradeNameArabic": "1008487",
        "partnerNameEnglish": "Xiaoping Mei",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "مؤسسة فردية",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3016825",
        "establishmentDate": "2021-10-15T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "زياوبينج   مى",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "1008487",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Establishment"
    },
    {
        "unifiedId": "8800000437",
        "expiryDate": "2022-10-18T00:00:00+04:00",
        "licenseStatusCode": "I",
        "legalFormCode": "L L C ",
        "partnerPercentage": "49",
        "tradeNameArabic": "أجكمبني ذ.م.م",
        "partnerNameEnglish": "Abbas Anas Naganathan",
        "partnerTypeEnglish": "Individual",
        "partnerNationalityArabic": "الهند",
        "legalFormArabic": "شركة ذات مسؤولية محدودة",
        "partnerNationalityCode": "IND",
        "tradeLicenseNo": "CN-3016973",
        "establishmentDate": "2021-10-19T00:00:00+04:00",
        "partnerTypeCode": "I N ",
        "issueDate": null,
        "IsAudited": false,
        "issuePlaceEnglish": "Abu Dhabi",
        "issuePlaceArabic": "أبو ظبي",
        "isSuspended": "N",
        "licenseStatusEnglish": "Issued",
        "partnerNameArabic": "عباس انس  ناجاناثان",
        "partnerNationalityEnglish": "India",
        "licenseStatusArabic": "اصدرت الرخصة",
        "tradeNameEnglish": "AGGCOMPANY L.L.C.",
        "partnerTypeArabic": "فرد",
        "legalFormEnglish": "Limited Liability Company"
    }
]