{
    "success": true,
    "message": "Success",
    "data": {
        "status": "200",
        "message": "Success",
        "MessageAr": "",
        "traceId": "720664",
        "code": "200",
        "result": [
            {
                "in_type_ar": " ",
                "localLaborAdministrative": " ",
                "expiryDate": "2022-10-09T00:00:00+04:00",
                "companyFaxNumber": " ",
                "LicenseStatusARB": "اصدرت الرخصة",
                "trackingNo": " ",
                "branch_type_ar": " ",
                "adcciNo": "8800000404",
                "in_type_en": " ",
                "tradeNameNo": "TN-3016453",
                "branch_type_en": " ",
                "licenseNo": "CN-3016489",
                "addressDetail": [
                    {
                        "Building": " مبنى -  السيد سهيل حمد محمد مرزوق  و اخرين -  133 : شارع على بن أبى طالب",
                        "POBox": "0",
                        "Landline": " ",
                        "FloorNo": " 133 : شارع على بن أبى طالب",
                        "Area": "وسط المدينة -  حي الحميرة",
                        "City": "العين",
                        "CountryCode": "+971"
                    }
                ],
                "IDB_Details": [],
                "SERVICE_AGENT_CONTRACT_EN": null,
                "SpecificLocation": null,
                "foreignLaborTechnical": " ",
                "exceptionTradeName": "No",
                "tenancyExpDate": "2019-01-01T00:00:00+04:00",
                "clasification_en": "Normal",
                "LeaseStartDate": null,
                "establishment_Date": "2021-10-10T00:00:00+04:00",
                "SERVICE_AGENT_CONTRACT_AR": null,
                "officialEmail": " ",
                "clasification_ar": "Normal",
                "companyCity": " ",
                "LeaseNumber": null,
                "AllocatedQuota": [],
                "TenantName": null,
                "industry_type_ar": " ",
                "tawtheeqNum": "193175",
                "paidCapital": "From AED 1 million up to AED 5 million",
                "SectorENG": null,
                "City": null,
                "quickLicense": " ",
                "isSuspended": "N",
                "issuePlaceEng": "Abu Dhabi",
                "BusinessAddressEN": " ",
                "LICENSE_TYPE_EN": null,
                "industry_ROWAD": " ",
                "LicenseStatusENG": "Issued",
                "social_media_type": " ",
                "officialDisclaimer": "No",
                "moiEstablishmentNo": " ",
                "LICENSE_TYPE_AR": null,
                "SectorARB": null,
                "foreignLaborAdministrative": " ",
                "mohreNo": "0",
                "isbranch": "N",
                "CoordinateX": "55.76338579",
                "IssuePlaceAR": "أبو ظبي",
                "CoordinateY": "24.22768285",
                "industry_type_en": " ",
                "revenuesSales": "From AED 1 million up to AED 5 million",
                "companyContactName": " ",
                "ecommerce_no": " ",
                "localLaborTechnical": " ",
                "companyLandLineNumber": " ",
                "LeaseEndDate": null,
                "gdrfaEstablishmentNo": " ",
                "LandArea": null,
                "autoCreated": "Yes",
                "companyEmail": " ",
                "officialMobile": " ",
                "expectedLabors": " ",
                "LeaseAmount": null,
                "legalFormArb": "شركة ذات مسؤولية محدودة",
                "activities": [
                    {
                        "activityCode": "4630111",
                        "activityNameEng": "Wholesale of Fresh Meat Trading ",
                        "activityNameArb": "تجارة اللحوم الطازجة - بالجملة "
                    }
                ],
                "LandLocationARB": null,
                "businessNameArb": "كوستكوفي للمواشى ذ.م.م",
                "countryOriginAr": "United Arab Emirates",
                "ZoneENG": null,
                "legalFormEng": "Limited Liability Company",
                "issueDate": null,
                "capital": 0,
                "countryOriginAn": "الإمارات العربية المتحدة",
                "LandLocationENG": null,
                "businessAddress": "وسط المدينة, حي الحميرة, 133 : شارع على بن أبى طالب, مبنى, السيد سهيل حمد محمد مرزوق  و اخرين",
                "gdrfaNo": 0,
                "partners": [
                    {
                        "nationalityAr": "الهند",
                        "referenceContactId": "41839665",
                        "LicenseNumber": " ",
                        "areaARB": " ",
                        "SNameAr": "كتان اتيف",
                        "typeArb": "فرد",
                        "representativeTypeArb": "شريك",
                        "pEmail": "sasun@mail.com",
                        "nationalityEn": "India",
                        "areaENG": " ",
                        "partnerSharePercentage": "49",
                        "NameEn": "Noushad Kuttan Aatif Mukhia",
                        "buildingNumber": " ",
                        "FNameAr": "نوشاد",
                        "idNumber": "784197339264026",
                        "NameAr": "نوشاد كتان اتيف موخيا",
                        "bDate": "1973-11-20T20:00:00Z",
                        "FNameEn": "Noushad",
                        "buildingNameENG": " ",
                        "streetARB": " ",
                        "contactId": "7245621",
                        "buildingNameARB": " ",
                        "streetENG": " ",
                        "representativeTypeEng": "Partner",
                        "LNameAr": "موخيا",
                        "typeEng": "Individual",
                        "LNameEn": "Kuttan Aatif Mukhia",
                        "phoneNumber": "+971 547934023"
                    },
                    {
                        "nationalityAr": "الإمارات العربية المتحدة",
                        "referenceContactId": "41839686",
                        "LicenseNumber": " ",
                        "areaARB": " ",
                        "SNameAr": "Abdulla  Idress Abdulla  Idress",
                        "typeArb": "فرد",
                        "representativeTypeArb": "شريك",
                        "pEmail": " ",
                        "nationalityEn": "United Arab Emirates",
                        "areaENG": " ",
                        "partnerSharePercentage": "51",
                        "NameEn": "Abdulla  Idress",
                        "buildingNumber": " ",
                        "FNameAr": "Abdulla  Idress",
                        "idNumber": "784-1987-3606406-8",
                        "NameAr": "Abdulla  Idress Abdulla  Idress Abdulla  Idress Abdulla  Idress",
                        "bDate": null,
                        "FNameEn": "Abdulla  Idress",
                        "buildingNameENG": " ",
                        "streetARB": " ",
                        "contactId": "7245622",
                        "buildingNameARB": " ",
                        "streetENG": " ",
                        "representativeTypeEng": "Partner",
                        "LNameAr": "Abdulla  Idress",
                        "typeEng": "Individual",
                        "LNameEn": null,
                        "phoneNumber": "+971 547934360"
                    }
                ],
                "ZoneARB": null,
                "social_media_account": " ",
                "businessLicCity": "العين",
                "social_media_web": " ",
                "businessNameEng": "COSTACOFEE LIVESTOCK L.L.C.",
                "companyBox": " "
            }
        ]
    },
    "error": {},
    "requestId": "ef87364f-150f-4f2d-90b0-9d361526b601"
}